# netlify.toml
[build]
  # 1) cd into the dashboard directory
  base    = "dashboard"
  # 2) install without frozen-lockfile, rebuild native modules, build & export
  command = "pnpm install --no-frozen-lockfile && pnpm rebuild && pnpm build && pnpm export"
  # 3) publish the Next.js export folder
  publish = "out"

[build.environment]
  NODE_ENV                          = "production"
  NEXT_PUBLIC_API_URL               = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

[dev]
  # for netlify dev to work locally
  command = "pnpm --filter dashboard dev"
  port    = 3000
