# netlify.toml

# ─ Override Netlify’s default install step so we skip the frozen‐lockfile check ──────
[install]
  command = "pnpm install --no-frozen-lockfile"

# ─ Build settings ───────────────────────────────────────────────────────────────────
[build]
  base    = "dashboard"                        # cd into your dashboard folder first
  command = "pnpm rebuild && pnpm build && pnpm export"
  publish = "dashboard/out"                    # static-export output directory

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"   # swap in real later
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"
