# netlify.toml

[build]
  # Move into the dashboard folder before building
  base    = "dashboard"
  # Run a non-frozen install so CI won’t break on lockfile drift
  install = "pnpm install --no-frozen-lockfile"
  # Rebuild native deps, build your Next.js app, then export static files
  command = "pnpm rebuild && pnpm build && pnpm export"
  # Publish the output folder relative to base
  publish = "out"

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"      # replace later
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"           # replace later

[dev]
  # For netlify CLI (`netlify dev`)
  command = "pnpm --filter dashboard dev"
  port    = 3000
