# netlify.toml

[build]
  base    = "dashboard"
  command = "pnpm install --no-frozen-lockfile && pnpm rebuild && pnpm build && pnpm export"
  publish = "dashboard/out"

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

[dev]
  command = "pnpm --filter dashboard dev"
  port    = 3000
