[build]
  base      = "dashboard"                  # 👈 run all commands from here
  command   = "pnpm install && pnpm rebuild && pnpm build && pnpm export"
  publish   = "out"                        # 👈 relative to `dashboard`
  functions = "netlify/functions"         # 👈 relative to `dashboard`
