# netlify.toml

[build]
  # cd into the dashboard folder first
  base    = "dashboard"
  # skip frozen-lockfile so CI install will succeed
  command = "pnpm install --no-frozen-lockfile && pnpm rebuild && pnpm build && pnpm export"
  # copy static output from Next.js export
  publish = "dashboard/out"

[build.environment]
  NODE_ENV                          = "production"
  NEXT_PUBLIC_API_URL               = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

# (optional) support Netlify CLI locally
[dev]
  command = "pnpm --filter dashboard dev"
  port    = 3000
