# netlify.toml
[build]
  base      = "dashboard"                                          # cd into dashboard first
  install   = "pnpm install --no-frozen-lockfile"                  # override Netlify’s default
  command   = "pnpm rebuild && pnpm build && pnpm export"          # your build+export
  publish   = "dashboard/out"                                      # static output

[build.environment]
  NODE_ENV                             = "production"
  NEXT_PUBLIC_API_URL                  = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY   = "pk_test_placeholder"

[dev]
  command = "pnpm --filter dashboard dev"
  port    = 3000
