# netlify.toml

# 1) Override the dependency install step:
[install]
  command = "pnpm install --no-frozen-lockfile"

# 2) Build settings
[build]
  base    = "dashboard"             # cd into your dashboard folder first
  command = "pnpm rebuild && pnpm build && pnpm export"
  publish = "dashboard/out"         # static-export output directory

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"   # swap in real later
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"
