[build]
  ## Change into the dashboard folder before running any commands
  base    = "dashboard"  
  ## Install without frozen-lockfile, rebuild native modules, run your build & export scripts
  command = "pnpm install --no-frozen-lockfile && pnpm rebuild && pnpm run build && pnpm run export"  
  ## After setting base, this path is relative to `dashboard/`
  publish = "out"  

[build.environment]
  NODE_ENV                         = "production"
  NEXT_PUBLIC_API_URL              = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

# Optional: support `netlify dev` locally
[dev]
  command = "pnpm --filter dashboard dev"
  port    = 3000
