# netlify.toml

[build]
  # ================ paths =================
  base    = "dashboard"          # cd into dashboard first
  publish = "dashboard/out"      # static export output

  # ================ command ============
  # allow drift between package.json & lockfile
  command = "pnpm install --no-frozen-lockfile && pnpm rebuild && pnpm build && pnpm export"

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"   # swap in real API URL later
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

  # ensure Netlify always passes --no-frozen-lockfile
  PNPM_FLAGS                         = "--no-frozen-lockfile"
