```toml
# netlify.toml

[build]
  # work from the dashboard subfolder
  base    = "dashboard"
  # override Netlify’s default frozen install so your lockfile mismatches won’t fail CI
  install = "pnpm install --no-frozen-lockfile"
  # rebuild any native deps, then build & export your Next.js‐static out folder
  command = "pnpm rebuild && pnpm build && pnpm export"
  # relative to `base`, this is where your static assets land
  publish = "out"

[build.environment]
  NODE_ENV                           = "production"
  NEXT_PUBLIC_API_URL                = "https://placeholder.local"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"

[dev]
  # for local `netlify dev` support
  command = "pnpm --filter dashboard dev"
  port    = 3000
```