"""
TORIS AI - GitHub Actions CI/CD Workflow
Implements automated testing, linting, and security scanning
"""
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          
      - name: Lint with ruff
        run: |
          ruff check .
          
      - name: Format check with black
        run: |
          black --check .
          
      - name: Type check with mypy
        run: |
          mypy torisai
          
      - name: Run tests
        run: |
          pytest -v tests/
          
      - name: Security scan with pip-audit
        run: |
          pip-audit

  build-and-push:
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/torisai-backend:latest
            ghcr.io/${{ github.repository }}/torisai-backend:${{ github.sha }}
          
      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile.ui
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/torisai-ui:latest
            ghcr.io/${{ github.repository }}/torisai-ui:${{ github.sha }}
